{% set name = "rxnmapper" %}
{% set version = "0.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/rxnmapper-{{ version }}.tar.gz
  sha256: cbe0a2ac582c83a8062a3b704c0ba6070a6bfd0fe2a2ede52c0e0fd872ee79a1

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 2

requirements:
  host:
    - python >=3.6
    - setuptools >=59.2.0
    - wheel
    - pip
  run:
    - python >=3.6
    - pandas >=1.0.3
    - rxn-chem-utils >=1.0.3
    - scipy >=1.4.1
    - pytorch >=1.5.0,<2.1
    - transformers >=4.0.0

test:
  imports:
    - rxnmapper
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/rxn4chemistry/rxnmapper
  summary: Reaction atom-mapping from transformers
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
