{% set name = "rxnmapper" %}
{% set version = "0.4.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/rxnmapper-{{ version }}.tar.gz
  sha256: 9ef84cbd2f538d982af84a2e485f50150e3fbe2a4aa76293aa3a858ba35d8eae

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=59.2.0
    - wheel
    - pip
  run:
    - python >={{ python_min }}
    - pandas >=1.0.3
    - rxn-chem-utils >=1.0.3
    - scipy >=1.4.1
    - pytorch >=1.5.0,<2.5
    - transformers >=4.0.0

test:
  imports:
    - rxnmapper
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/rxn4chemistry/rxnmapper
  summary: Reaction atom-mapping from transformers
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
